#!/usr/bin/env bash
# Adding a custom 404 page
# Always restart/reload nginx after changes

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/uchecom permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
