#!/usr/bin/env bash
# Installation and configuration of HAproxy on your lb-01 server.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.8.\

server_config=\
"
frontend http
         bind 0:80
         mode http
         default_backend web-server
backend web-server
        balance roundrobin
        server 263805-web-01 3.80.19.118:80 check
        server 263805-web-02 3.83.18.66:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
