#!/usr/bin/env bash
# Installation and configuration of HAproxy on your lb-01 server.

#apt-get install --no-install-recommends software-properties-common
#add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy=2.8.\*

# Backup haproxy default server config
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.original

server_conf=\
"
frontend http
         bind 0:80
         mode http
         default_backend web-server
backend web-server
        balance roundrobin
        server 263805-web-01 3.80.19.118:80 check
        server 263805-web-02 3.83.18.66:80 check
"

# shellcheck disable=SC2154
echo "$server_conf" | sudo tee -a /etc/haproxy/haproxy.cfg

# This enables haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start

sudo service haproxy restart
