#!/usr/bin/env bash
# Script manages a script using the subprocesses (start, stop and restart)

CMD=/var/run/my_process.pid
start() {
	bash ./manage_my_process &
	echo "$!" > "$CMD"
}

stop() {
       sudo kill -15 "$(cat "$CMD")" && rm -f "$CMD"
}

restart() {
	  stop
	  start
}

case "$1" in
     start)
	start
	echo "manage_my_process started"
	;;
     stop)
	stop
	echo "manage_my_process stopped"
	;;
     restart)
	restart
	echo "manage_my_process restarted"
	;;
     *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
