#!/usr/bin/env bash
# A script that displays "Best School" 10 times and "hi" & "Best School" after the 9th using while and if

n=0

while [ $n -lt 10 ]
do
    echo "Best School"
    if [ "$n" -eq 8 ]
    then
        echo "Hi"
    fi
    ((n++))
done
