#!/usr/bin/env bash
# Script displays numbers from 1 to 20 using while loop and case statement.

n=1

while [ $n -le 20 ]
do
	echo "$n"	
	case $n in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac

	((n++))
done
