#!/usr/bin/env bash
# Firewall installation and cofiguration-ufw.

echo -e "Updating\n"
sudo apt-get update

echo -e "Installing UFW\n"
sudo apt-get install -y ufw

echo -e "configuring UFW...\n"

# Deny Incoming & allow outgoing
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow certain ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enable firewall
sudo ufw enable

echo -e "Process Completed.\n"
